### ISSUE TITLE
Doesn't support passing a path for a new project

### ISSUE THREAD

**Issue by tlindsay** [crutchcorn/plop-pack-git-init#3]
I'm trying to use this to create a project generator. I'm aiming for an API like `$ my-script new project my-cool-new-project`.
I would expect this to create a directory `./my-cool-new-project/` if one doesn't already exist. In actuality, this pack tries to spawn a new `git init` process in that directory, which throws an `ENOENT` exception.

Should this be refactored to create the dir? Is it out of scope for this project? Am I doing something wrong? Struggling to see how this project is useful without this feature.

Plopfile snippet:
```js
  plop.setGenerator('new project', {
    description: 'creates a new project',
    prompts: [
      {
        type: 'string',
        name: 'name'
      }
    ],
    actions(data) {
      return [
        {
          type: 'gitInit',
          path: `${process.cwd()}/${data.name}/`,
          verbose: true
        }
      ];
    }
  });
```

**Comment by crutchcorn** [comment]
I'd argue that creating a new directory is out-of-scope for this project. What I would suggest doing is have a template with a `.gitkeep` file in there, allowing you to `add` a file. Otherwise, you could create a new `plop-pack-new-folder` plugin that might do what you're looking for.

The reason I made this package is that I have a CLI utility (private) that has a template that we're using at my company as a project's baseline. Once the folder is added, it then moves forward with `git init` and adding everything into a first commit. This way, it acts like most other code generators that publish a first commit once the template is settled down (CRA, Angular CLI, Vue CLI)
